# Practice 2: Purchase Data

Using the file "Purchase_Data.csv," which contains data on purchases made at a Chinese supermarket for various products, execute the following tasks to extract information based on specific requirements.

Import pandas

In [1]:
#Write your code here
import pandas as pd

Read this csv into a dataframe called df_data

In [7]:
#Write your code here
df_data = pd.read_csv("Purchase_Data.csv")

Use the dtypes attribute to view how each column is stored

In [13]:
#Write your code here
df_data.dtypes

invoice_number    float64
invoice_time       object
store_id           object
product_id          int64
category_id         int64
num_item          float64
price             float64
dtype: object

Slice the <b>first two columns</b> using .loc and store the result in a variable called result_1.

In [19]:
#Write you code here
result_1 = df_data.loc[:, ["invoice_number", "invoice_time"]]
result_1

      invoice_number   invoice_time
0       2.020000e+11  7/15/15 10:45
1       2.020000e+11  7/15/15 12:16
2       2.020000e+11  7/15/15 12:16
3       2.020000e+11  7/15/15 12:16
4       2.020000e+11  7/15/15 12:16
...              ...            ...
5377    2.020000e+11   9/5/15 23:07
5378    2.020000e+11   9/5/15 23:23
5379    2.020000e+11   9/5/15 23:24
5380    2.020000e+11   9/5/15 23:32
5381    2.020000e+11   9/5/15 23:38

[5382 rows x 2 columns]

Slice the <b>first two rows</b> using .loc and store the result in a variable called result_2.

In [23]:
#Write you code here
result_2 = df_data.loc[[1,2], :]
result_2

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0

Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [28]:
#Write your code here
results_3 = df_data.iloc[0:4, 0:5]
results_3

   invoice_number   invoice_time store_id  product_id  category_id
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [29]:
#Write your code here
result_4 = df_data.loc[[0,4,6], ["invoice_time", "price"]]
result_4

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [30]:
#Write your code here
num_rows = df_data.shape[0]

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [32]:
#Write your code here
print(df_data.iloc[num_rows-1])

invoice_number    202000000000.0
invoice_time        9/5/15 23:38
store_id                    G619
product_id              23030206
category_id               210101
num_item                     1.0
price                        2.0
Name: 5381, dtype: object

------------------------------------------- End of Practice-------------------------------------------