# Practice 1: Salaries

Utilising the file named 'Staff_Salaries.csv' which holds data regarding the salaries of academic staff members across different positions, perform a series of tasks to extract information according to particular requirements or answer the questions.

Import pandas

In [1]:
import pandas as pd

Read this csv into a dataframe called df

In [15]:
staff_salaries = pd.read_csv("staff_salaries.csv")
df = pd.read_csv("staff_salaries.csv")
df

     position        discipline  phd  service hours  gender  salary
0        Prof  Computer Science   56             49    Male  186960
1        Prof         Economics   12              6    Male   93000
2        Prof         Education   23             20    Male  110515
3        Prof               Art   15             31    Male  131205
4        Prof  Computer Science   20             18    Male  104800
..        ...               ...  ...            ...     ...     ...
73       Prof         Education   18             10  Female  105450
74  AssocProf    Social Science   19              6  Female  104542
75       Prof  Computer Science   17             17  Female  124312
76       Prof        Psychology   28             14  Female  109954
77       Prof               Law   23             15  Female  109646

[78 rows x 6 columns]

What are the columns names?

In [24]:
print(df.columns)

Index(['position', 'discipline', 'phd', 'service hours', 'gender', 'salary'], dtype='object')

What are data types of columns we have in this data frame?

In [28]:
df.dtypes

position         object
discipline       object
phd               int64
service hours     int64
gender           object
salary            int64
dtype: object

How many rows and columns does this dataframe have?

In [31]:
print(f"Number of rows: {df.shape[0]} and columns: {df.shape[1]}")

Number of rows: 78 and columns: 6

How many academic staff are in each discipline?

In [35]:
unique_staff = staff_salaries['position'].value_counts()
unique_staff

position
Prof         46
AsstProf     19
AssocProf    13
Name: count, dtype: int64

Create a new variable called selected_staff that includes only the position, gender, and salary columns from the dataframe, then display it on the screen.

In [42]:
selected_staff = staff_salaries[["position", "gender", "salary"]]
selected_staff

     position  gender  salary
0        Prof    Male  186960
1        Prof    Male   93000
2        Prof    Male  110515
3        Prof    Male  131205
4        Prof    Male  104800
..        ...     ...     ...
73       Prof  Female  105450
74  AssocProf  Female  104542
75       Prof  Female  124312
76       Prof  Female  109954
77       Prof  Female  109646

[78 rows x 3 columns]

Write the selected columns from the previous task to a new csv file called selected_salaries.csv

In [46]:
selected_staff = staff_salaries[["position", "gender", "salary"]]
selected_staff.to_csv("selected_salaries.csv")

-------------------------------End of Practice 1 --------------------------------------